export const theme = {
  colors: {
    background: '#F5F5F7',
    surface: '#FFFFFF',
    primary: '#1A1B4B',       // Navy dark blue
    primaryLight: '#2D2E7A',
    accent: '#E8472A',        // Orange-red
    accentLight: '#FF6B4A',
    success: '#2ECC71',
    successBg: '#E8F8F0',
    warning: '#F39C12',
    warningBg: '#FEF9E7',
    danger: '#E74C3C',
    dangerBg: '#FDEDEC',
    textMain: '#1A1B4B',
    textSub: '#4A4B6A',
    textMuted: '#9B9BB5',
    border: '#E8E8F0',
    cardShadow: '#1A1B4B',
    // legacy compat
    primaryDark: '#0D0E2E',
    successGreen: '#2ECC71',
    successPillBg: '#E8F8F0',
    cardWhite: '#FFFFFF',
    scannerGradientStart: '#1A1B4B',
    scannerGradientEnd: '#2D2E7A',
    folderGradientStart: '#EAE6FF',
    folderGradientEnd: '#F9F8FF',
    borderLight: '#E8E8F0',
    textMuted2: '#9B9BB5',
  },
  spacing: { xs: 4, s: 8, m: 16, l: 24, xl: 32 },
  borderRadius: { s: 8, m: 14, l: 20, xl: 28, round: 999 },
  typography: {
    header: { fontSize: 20, fontWeight: '800' as const, color: '#1A1B4B' },
    title: { fontSize: 18, fontWeight: '700' as const, color: '#1A1B4B' },
    subtitle: { fontSize: 14, fontWeight: '600' as const },
    body: { fontSize: 13, fontWeight: '400' as const },
    small: { fontSize: 11, fontWeight: '500' as const },
  },
  shadows: {
    card: {
      shadowColor: '#1A1B4B',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.06,
      shadowRadius: 12,
      elevation: 3,
    },
    cardHover: {
      shadowColor: '#1A1B4B',
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.08,
      shadowRadius: 16,
      elevation: 6,
    },
  },
  animation: {
    fast: 200,
    normal: 300,
    slow: 400,
    fadeIn: 600,
  },
};

// Web-safe icon map — renders as text on all platforms including Vercel web
export const Icon: Record<string, string> = {
  // Navigation
  home: '⊞',
  claims: '◎',
  analytics: '▦',
  profile: '◉',
  back: '←',
  forward: '→',
  chevronRight: '›',
  close: '✕',
  settings: '⚙',
  // Status
  check: '✓',
  checkCircle: '✔',
  cross: '✗',
  crossCircle: '✘',
  alert: '⚠',
  info: 'ℹ',
  // Weather / triggers
  rain: '🌧',
  sun: '☀',
  heat: '🌡',
  cloud: '☁',
  wind: '💨',
  flood: '🌊',
  // Transport
  car: '🚗',
  bike: '🚴',
  truck: '🚚',
  delivery: '🛵',
  // Finance
  rupee: '₹',
  wallet: '💳',
  payout: '💸',
  bank: '🏦',
  // UI
  shield: '🛡',
  shieldCheck: '✅',
  location: '📍',
  person: '👤',
  star: '⭐',
  bulb: '💡',
  flash: '⚡',
  fire: '🔥',
  lock: '🔒',
  eye: '👁',
  eyeOff: '🙈',
  phone: '📱',
  mail: '✉',
  time: '🕐',
  calendar: '📅',
  document: '📄',
  receipt: '🧾',
  gift: '🎁',
  notification: '🔔',
  search: '🔍',
  edit: '✏',
  trash: '🗑',
  logout: '↩',
  verified: '✅',
  // Arrows
  arrowUp: '↑',
  arrowDown: '↓',
  arrowRight: '→',
  arrowLeft: '←',
  // Misc
  dot: '•',
  dotFilled: '●',
  dotEmpty: '○',
  minus: '−',
  plus: '+',
  percent: '%',
  food: '🍔',
  grocery: '🛒',
  ecommerce: '📦',
  logistics: '🚛',
  airplane: '✈',
  strike: '✊',
  pollution: '🏭',
  monsoon: '⛈',
  badge: '🏅',
  robot: '🤖',
  send: '➤',
};
